// config
@fhirUrl = http://localhost:8080/fhir
@endorserStaticUrl = http://localhost:3000/endorser/static
@endorserApiUrl = http://localhost:3000/endorser/api

@organizationName = Test Org
@developerName = MHM

### GET Endorser static

GET {{endorserStaticUrl}}


### POST - Create Developer
# @name createDeveloper
POST {{endorserApiUrl}}/developer
Accept: application/json
Content-Type: application/json

{
  "organizationName": "{{organizationName}}",
  "developerName": "{{developerName}}"
}


### GET - Developer by ID
# @name getDeveloper
@developerId = {{createDeveloper.response.body.id}}
GET {{endorserApiUrl}}/developer/{{developerId}}

### DELETE - Developer by ID
# @name deleteDeveloper
DELETE {{endorserApiUrl}}/developer/{{developerId}}


### POST - Create App
# @name createApp
POST {{endorserApiUrl}}/developer/{{developerId}}/app
Accept: application/json
Content-Type: application/json

{
  "sub": "https://mysub.example.com",
  "client_name": "The best health app available",
  "redirect_uris": ["https://mysub.example.com/redirect", "mysub://redirect"]
}

### Extract result from POST
@appId = {{createApp.response.body.id}}

### GET an endorsement for the app

GET {{endorserApiUrl}}/developer/{{developerId}}/app/{{appId}}/endorsement

