// config
@fhirUrl = http://localhost:8080/fhir
@endorserStaticUrl = http://localhost:3000/endorser/static
@endorserApiUrl = http://localhost:3000/endorser/api
@ehrApiUrl = http://localhost:3000/ehr/api

@organizationName = Test Org
@developerName = MHM

### GET Endorser static

GET {{endorserStaticUrl}}


### POST - Create Developer
# @name createDeveloper
POST {{endorserApiUrl}}/developer
Accept: application/json
Content-Type: application/json

{
  "organizationName": "{{organizationName}}",
  "developerName": "{{developerName}}"
}


### GET - Developer by ID
# @name getDeveloper
@developerId = {{createDeveloper.response.body.id}}
GET {{endorserApiUrl}}/developer/{{developerId}}

### DELETE - Developer by ID
# @name deleteDeveloper
DELETE {{endorserApiUrl}}/developer/{{developerId}}


### POST - Create App
# @name createApp
POST {{endorserApiUrl}}/developer/{{developerId}}/app
Accept: application/json
Content-Type: application/json

{
  "sub": "https://mysub.example.com",
  "client_name": "The best health app available",
  "redirect_uris": ["https://mysub.example.com/redirect", "https://mysub.example.com/redirect-2"]
}


### POST - Create App (UI Testing)
# @name createAppTest
POST {{endorserApiUrl}}/developer/{{developerId}}/app
Accept: application/json
Content-Type: application/json

{
  "sub": "http://localhost:3000/app",
  "client_name": "UDAP Spike App",
  "redirect_uris": [
    "http://localhost:3000/app/oauth-redirect",
    "http://localhost:3002/"
  ]
}

### Extract result from POST
@appId = {{createApp.response.body.id}}

### GET an endorsement for the app
# @name getEndorsement

GET {{endorserApiUrl}}/developer/{{developerId}}/app/{{appId}}/endorsement

### Send endorsement to EHR
@endorsement = {{getEndorsement.response.body.endorsement}}

POST {{ehrApiUrl}}/oauth/register
Accept: application/json
Content-Type: application/json

{
  "udap": "1",
  "certifications": ["{{endorsement}}"]
}

